name: Deploy Penkode Framework Theme

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'bin/**'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Penkode Framework via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          source: './'  # Directorio local a subir (ajústalo según sea necesario)
          target: '/www/public_html/01-penkode.com/framework/wp-content/themes/penkode-framework'
          rm: true  # Opcional: limpia archivos en el destino antes de copiar