name: Deploy Penkode Framework Theme

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'bin/**'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Penkode Framework
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          protocol: 'sftp'   # Cambiar a 'ftp' si solo soporta FTP
          port: ${{ secrets.SFTP_PORT }}
          local-dir: './'  # Directorio local a desplegar
          server-dir: '/www/public_html/01-penkode.com/framework/wp-content/themes/penkode-framework'
          log-level: 'verbose'
